# Generated by Django 5.1.5 on 2025-07-19 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_order_products_remove_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='review',
            name='charms',
            field=models.ManyToManyField(blank=True, to='api.charm'),
        ),
        migrations.AddField(
            model_name='review',
            name='gift_sets',
            field=models.ManyToManyField(blank=True, to='api.giftsetorbundlemonthlyspecial'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='products',
            field=models.ManyToManyField(blank=True, to='api.product'),
        ),
    ]
