# Generated by Django 5.1.5 on 2025-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_weight_review_charms_review_gift_sets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('collection', 'Collection'), ('awaiting_shipment', 'Awaiting Shipment'), ('on_shipping', 'On Shipping'), ('shipped', 'Shipped'), ('pending', 'Pending'), ('packing', 'Packing'), ('delivery', 'Delivery'), ('done', 'Done'), ('not_accepted', 'Not Accepted')], default='pending', max_length=20),
        ),
    ]
