# Generated by Django 5.1.5 on 2025-07-29 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cartitem_message_orderitem_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
