# Generated by Django 5.1.5 on 2025-07-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
