# Generated by Django 5.1.5 on 2025-07-29 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_review_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='charms',
            field=models.ManyToManyField(blank=True, null=True, to='api.charm'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gift_sets',
            field=models.ManyToManyField(blank=True, null=True, to='api.giftsetorbundlemonthlyspecial'),
        ),
        migrations.AlterField(
            model_name='review',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='api.product'),
        ),
        migrations.CreateModel(
            name='ReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
