# Generated by Django 5.1.5 on 2025-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_review_charms_alter_review_gift_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='charms',
            field=models.ManyToManyField(blank=True, to='api.charm'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gift_sets',
            field=models.ManyToManyField(blank=True, to='api.giftsetorbundlemonthlyspecial'),
        ),
        migrations.AlterField(
            model_name='review',
            name='products',
            field=models.ManyToManyField(blank=True, to='api.product'),
        ),
    ]
